config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :noticia, only: [:show ]
  resources :comments, only: [:create]
  root to: 'pages#home'

  namespace :admin do
  	resources :notice
  end

  namespace :api do
  	resources :notice, only: [:index] 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/noticia.rb
class Noticia < ApplicationRecord

	has_many :comments 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments       
end

app/controllers/admin/notice_controller.rb
class Admin::NoticeController < ApplicationController
	before_action :authenticate_user!
  layout 'admin'
  def index
  	@noticias = Noticia.all
  end

  def show
  	@noticia = Noticia.find(params[:id])
  end

  def new
  	@noticia = Noticia.new
  end

  def create
		@noticia = Noticia.new(noticia_params)

		if @noticia.save
		  redirect_to admin_notice_index_path
		else
		render :new
		end
  end

  def edit
  	@noticia = Noticia.find(params[:id])
  end

  def update
  	@noticia = Noticia.find(params[:id])

  	if @noticia.update(noticia_params)
  		redirect_to admin_notice_index
  	else
  		render :new
  	end
  end

  def destroy
		@noticia = Noticia.find(params[:id])
		@noticia.destroy
		flash[:notice] = "La investigacion se ha eliminado"
		redirect_to admin_notice_index_path
	end

  private
  def noticia_params
  	params.require(:noticia).permit(:title, :description, :first_notice, :image_url)
  end
end

app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController
	
end

app/controllers/api/notice_controller.rb
class Api::NoticeController < Api::BaseController
	def index
		@notices = Noticia.all  
		render :json => @notices
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!

	def create
		@noticia = Noticia.find(params[:comment][:noticia_id])
		comment = Comment.new(comment_params)
		comment.user_id = current_user.id
		if comment.save
			redirect_to @noticia
		end

	end

	private
  def comment_params
    params.require(:comment).permit(:description, :noticia_id)
  end
end

app/controllers/noticia_controller.rb
class NoticiaController < ApplicationController
  def show
 	@noticia = Noticia.find(params[:id])
 	@noticias = Noticia.all
 	@comment = @noticia.comments.build
 	puts @comment.inspect
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 layout :layout_by_resource
 
 def home
 	@noticias = Noticia.where(first_notice: false)
	@noticia = Noticia.find_by(first_notice: true)
 end


  private
	def layout_by_resource
		if devise_controller?
		  "devise"
		else
		  "application"
		end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/notice/edit.html.erb
<br>
<br>
<br>
<div class="container">
	<div class="row">
		<div class="col">
			<h1>Editar investigacion:</h1>
			<h3><%= @noticia.title %></h3>
		</div>
	</div>
</div>

<div class="container">
  <div class="row">
    <div class="col">
      <div class="col-md-8 jumbotron" style="margin: 0 auto;">
        <%= form_for @noticia, url: admin_notice_path do |f| %>
        <div class="card-body">
          <div class="form-group">
            <%= f.label :Titulo %>
            <%= f.text_field :title, class: "form-control", autofocus: true %>
          </div>
          <div class="form-group">
            <%= f.label :Autor %>
            <%= f.text_field :author, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :Descripcion %>
            <%= f.text_area :description, rows: 4, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :url_imagen %>
            <%= f.url_field :image_url, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :Primera_investigacion_del_index %>
            <%= f.text_field :first_notice, class: "form-control" %>
          </div>
        </div>
        <div class="card-footer text-right">
          <%= f.submit :Listo, class: "btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/notice/index.html.erb
<div class="container">
  <br>
  <br>
  <br>
  <br>
  <div class="row">
    <div class="col">
      <table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Autor</th>
      <th scope="col">Fecha de publicacion</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @noticias.each do |i| %>
    
    <tr>
      <td><%= i.title %></td>      
      <td> <%= i.author %></td>
      <td> <%= i.publication_date %></td>
      <td> <%= link_to 'Ver', admin_notice_path(i), class: "btn btn-link" %></td>
      <td> <%= link_to 'Editar', edit_admin_notice_path(i), class: "btn btn-link" %></td>
      <td><%= link_to "Eliminar", admin_notice_path(i), class: "btn btn-link", method: :delete, data: { confirm: "¿Estás seguro de eliminar esta investigacion?" } %></td>
    </tr>
    <% end %>
  </tbody>
</table>
    </div>
  </div>
</div>  

app/views/admin/notice/new.html.erb
<br>
<br>
<br>
<div class="container">
	<div class="row">
		<div class="col">
			<h1>Nueva investigacion:</h1>
		</div>
	</div>
</div>

<div class="container">
  <div class="row">
    <div class="col">
      <div class="col-md-8 jumbotron" style="margin: 0 auto;">
        <%= form_for @noticia, url: admin_notice_index_path do |f| %>
        <div class="card-body">
          <div class="form-group">
            <%= f.label :Titulo %>
            <%= f.text_field :title, class: "form-control", autofocus: true %>
          </div>
          <div class="form-group">
            <%= f.label :Autor %>
            <%= f.text_field :author, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :Descripcion %>
            <%= f.text_area :description, rows: 4, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :url_imagen %>
            <%= f.url_field :image_url, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :Primera_investigacion_del_index %>
            <%= f.text_field :first_notice, class: "form-control" %>
          </div>
        </div>
        <div class="card-footer text-right">
          <%= f.submit :Listo, class: "btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/notice/show.html.erb
<div class="container">
	<br>
	<br>
	<br>
	<%= link_to 'Volver', admin_notice_index_path ,class: "btn btn-link" %>
	<br>
	<div class="row">
		<div class="col">
			<p> Fecha de publicacion: <%= @noticia.publication_date %></p>
		</div>
		<div class="col">
			<p>Invesigacion Prioritaria: <%= @noticia.first_notice %></p>
		</div>
	</div>
	<div class="row">
		<div class="col">
			<h2><%= @noticia.title %></h2>
		</div>
	</div>
	<div class="row">
		<div class="col">
			<p> autor: <%= @noticia.author %></p>
		</div>
	</div>
	<div class="row">
		<div class="col">
			
		</div>
	</div>
	<hr>
	<div class="row">
		<div class="col">
			<p><%= @noticia.description %></p>
			<hr>
			<p>URL de la imagen: </p>
			<a  target= "blanck"href= <%= @noticia.image_url %> ><%= @noticia.image_url %> </a>
		</div>
		<div class="col">
			<%= image_tag(@noticia.image_url, class: "img-fluid") %>
		</div>
	</div>
</div>

app/views/application/_admin.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="#">Administrador |  Informante Virtual</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <%= link_to 'Crear nueva noticia', new_admin_notice_path ,class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/application/_footer.html.erb
<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
      <p class="text-center text-white">Copyright &copy; Informante Virtual 2019</p>
    </div>
</footer>

app/views/application/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="#">Informante Virtual</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <%= link_to 'Home |', root_path ,class: "nav-link" %>
        </li>
          <% if signed_in? %>
            <li class="nav-item ml-auto">
              <%= link_to "Salir", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item ml-auto">
            <%= link_to "Registrarse", new_user_registration_path, class: "nav-link" %>              
            </li>
            <li class="nav-item ml-auto">
              <%= link_to "Ingresar", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InfoVirtual</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'admin' %>
    <%= yield %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InfoVirtual</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navbar' %>
    <%= yield %>
    <%= render 'footer' %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InfoVirtual</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/noticia/show.html.erb
<!-- Page Content -->
    <div class="container">
			<br><br>
      <div class="row">
        <!-- Post Content Column -->
        <div class="col-lg-8">
          <!-- Title -->
          <h1 class="mt-4"><%= @noticia.title %></h1>
          <!-- Author -->
          <p class="lead">
            Investiga
            <a href="#"><%= @noticia.author %></a>
          </p>
          <hr>
          <!-- Date/Time -->
          <p>Investiga <%= @noticia.publication_date %></p>
          <hr>
          <!-- Preview Image -->
          <%= image_tag(@noticia.image_url, :class =>"img-fluid")  %>
          <hr>
          <!-- Post Content -->
          <p class="lead"> <%= @noticia.description %></p>
          <hr>
          <!-- Comments Form -->
          <div class="card my-4">
            <h5 class="card-header">Comentario:</h5>
            <div class="card-body">
              <%= form_for @comment  do |f| %>
                <div class="card-body">
                  <div class="form-group">
                    <%= f.hidden_field :noticia_id %>
                    <%= f.text_area :description, rows: 4, class: "form-control" %>
                  </div>
                </div>
                <div class="card-footer text-right">
                  <%= f.submit :Listo, class: "btn btn-primary" %>
                </div>
              <% end %>
            </div>
          </div>

          <!-- Single Comment -->
          <% @noticia.comments.each do |i|%>
            <div class="media mb-4">
              <div class="media-body">
                
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <%= i.description %>
              </div>
            </div>
          <% end %>
        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4 sidebar">
          <!-- Categories Widget -->
          <div class="card my-4">
            <h5 class="card-header">Investigaciones</h5>
            <div class="card-body">
              <div class="row">
                <div class="col-lg-12">
                  <ul class="list-unstyled mb-0">
                    <% @noticias.each do |i| %>
                      <li>
                        <%= link_to i.title, noticium_path(i) %>
                      </li>
                      <hr>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container -->

app/views/pages/_content.html.erb
 <!-- Page Content -->
    <div class="container">
      <br>
      <br>
      <!-- Heading Row -->
      <div class="row my-4 container-hero">
        <div class="col-lg-8">
          <%=image_tag(@noticia.image_url, class: "img-fluid rounded")%>
        </div>
        <!-- /.col-lg-8 -->
        <div class="col-lg-4">
          <h3><%= @noticia.title %></h3>
          <hr>
          <p><%= truncate(@noticia.description, length:300) %></p>
          <%= link_to 'ver mas', noticium_path(@noticia), class: "btn btn-primary" %>
        </div>
        <!-- /.col-md-4 -->
      </div>
      <!-- /.row -->

      <!-- Call to Action Well -->
      <div class="card text-white bg-secondary my-4 text-center">
        <div class="card-body">
          <p class="text-white m-0">En este sitio web encontrara serie de eventos que se encuentran actualmente activas con investigaciones y demas, <span>Si usted tiene informacion confidencial de lo que se muestre en este portal puede contactarnos o dejarnos un comentario haciendo saber la informacion que tenga para hacer parte a la investigacion del mismo</span></p>
        </div>
      </div>

      <!-- Content Row -->
      <div class="row">
        <% @noticias.each do |i| %>
          <div class="col-md-4 mb-4">
            <div class="card h-100">
              <div class="card-body">
                <h4 class="card-title"><%= i.title %></h4>
                <p class="card-text"><%= truncate(i.description, length:100)  %></p>
              </div>
              <div class="card-footer">
                <%= link_to 'ver mas', noticium_path(i), class: "btn btn-primary" %>
              </div>
            </div>
        </div>
        <% end %>
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container -->

app/views/pages/home.html.erb
<%= render "content" %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>